ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/numpy/numpydoc
    rev: v1.10.0
    hooks:
      - id: numpydoc-validation
        files: ^pyvista_tui/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb, "1000"]
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      # - id: no-commit-to-branch
      #   args: [--branch, main]
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: ["--fix", "--show-fixes"]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.36.1
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: local
    hooks:
      - id: format-justfile
        name: Format justfile
        entry: just --fmt --unstable
        language: system
        files: '(^|/)justfile$|\.just$'
        pass_filenames: false
